export const HEADER = {
  MOBILE_HEIGHT: 64,
  MAIN_DESKTOP_HEIGHT: 88,
  DESKTOP_HEIGHT: 92,
  DESKTOP_OFFSET_HEIGHT: 92 - 32,
};

export const SIDEBAR = {
  BASE_WIDTH: 260,
  WIDTH: 280,
  COLLAPSE_WIDTH: 88,
  //
  ITEM_ROOT_HEIGHT: 48,
  ITEM_SUB_HEIGHT: 40,
  ITEM_HORIZONTAL_HEIGHT: 32,
};

export const ICON = {
  NAVBAR_ITEM: 22,
  NAVBAR_ITEM_HORIZONTAL: 20,
};